# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AutoLayout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'MBProgressHUD', '~> 1.1.0'
	pod 'IQKeyboardManager'
	pod 'SDWebImage', '~> 4.0'
	pod 'Masonry'
# 友盟 移动统计
    pod 'UMCCommon'
    pod 'UMCCommonLog'
    pod 'UMCAnalytics'
    pod 'UMCSecurityPlugins'
# logger
    pod 'CocoaLumberjack'
    pod 'ReactiveObjC', '~> 3.1.0'


  # Pods for AutoLayout

end
